# Generated by Django 4.2.26 on 2025-11-08 07:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='House',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('house_type', models.CharField(choices=[('single_room', 'Single Room'), ('bedsitter', 'Bedsitter'), ('one_bedroom', 'One Bedroom'), ('two_bedroom', 'Two Bedroom'), ('three_bedroom', 'Three Bedroom'), ('studio', 'Studio Apartment'), ('double_room', 'Double Room')], max_length=20)),
                ('description', models.TextField()),
                ('location', models.CharField(help_text='e.g. Ongata Romgai, Kajiado', max_length=400)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True)),
                ('rent', models.DecimalField(decimal_places=2, help_text='Monthly rent in KES', max_digits=10)),
                ('deposit', models.DecimalField(decimal_places=2, help_text='House deposit required', max_digits=10)),
                ('house_number', models.CharField(max_length=20)),
                ('floor_number', models.CharField(blank=True, max_length=10, null=True)),
                ('listing_fee_paid', models.BooleanField(default=False)),
                ('date_posted', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='houses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'House Listing',
                'verbose_name_plural': 'House Listings',
                'ordering': ['-date_posted'],
            },
        ),
        migrations.CreateModel(
            name='HouseTerm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term', models.CharField(help_text='e.g. No pets, 1 month deposit', max_length=700)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('house', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='terms', to='houses.house')),
            ],
            options={
                'verbose_name': 'House term',
                'verbose_name_plural': 'House terms',
                'ordering': ['-created_at', '-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='HouseImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='house/images/')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('house', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='houses.house')),
            ],
            options={
                'verbose_name': 'House image',
                'verbose_name_plural': 'House images',
                'ordering': ['-created_at', '-updated_at'],
            },
        ),
    ]
