# Generated by Django 4.2.26 on 2025-11-12 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='houseterm',
            name='term',
            field=models.TextField(help_text='e.g. No pets, 1 month deposit', max_length=2000),
        ),
    ]
