# Generated by Django 4.2.26 on 2025-11-17 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0002_alter_houseterm_term'),
    ]

    operations = [
        migrations.AlterField(
            model_name='house',
            name='floor_number',
            field=models.CharField(blank=True, help_text='e.g  Ground Floor, Bungalow, Block A, Plot 5, or leave empty', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='house',
            name='location',
            field=models.CharField(help_text='e.g. Ongata Rongai, Kajiado', max_length=400),
        ),
    ]
