# Generated by Django 5.2.8 on 2025-11-27 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0004_activity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='activity_type',
            field=models.CharField(choices=[('house_posted', 'House Posted'), ('house_updated', 'House Updated'), ('profile_updated', 'Profile Updated'), ('password_changed', 'Password Changed'), ('house_viewed', 'House Viewed'), ('delete_house', 'House Deleted'), ('review_posted', 'Review Posted')], max_length=20),
        ),
    ]
