# Generated by Django 5.2.8 on 2025-12-01 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0007_alter_activity_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='house',
            name='is_active',
            field=models.BooleanField(default=False, help_text='House is visible to public'),
        ),
        migrations.AddField(
            model_name='house',
            name='payment_status',
            field=models.CharField(choices=[('unpaid', 'Unpaid'), ('pending', 'Payment Pending'), ('paid', 'Paid')], default='unpaid', max_length=20),
        ),
        migrations.AlterField(
            model_name='activity',
            name='activity_type',
            field=models.CharField(choices=[('house_posted', 'House Posted'), ('edit_profile', 'Edited Profile'), ('edit_company_profile', 'Edited Company Profile'), ('house_updated', 'House Updated'), ('profile_updated', 'Profile Updated'), ('password_changed', 'Password Changed'), ('house_viewed', 'House Viewed'), ('delete_house', 'House Deleted'), ('review_posted', 'Review Posted'), ('make_payment', 'Paid for a house.')], max_length=20),
        ),
    ]
