# Generated by Django 5.2.8 on 2025-12-03 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0008_house_is_active_house_payment_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='house',
            name='listing_fee_paid',
        ),
    ]
