# Generated by Django 5.2.8 on 2025-11-24 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_profile_company_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='national_id',
            field=models.CharField(blank=True, help_text='National ID or Passport Number', max_length=20, null=True),
        ),
    ]
