# Generated by Django 5.2.8 on 2025-11-24 20:59

import phonenumber_field.modelfields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_profile_national_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, help_text='e.g. +254712345678', max_length=128, null=True, region='KE'),
        ),
    ]
