# Generated by Django 5.2.8 on 2025-11-30 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_profile_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='user_type',
            field=models.CharField(choices=[('landlord', 'Landlord'), ('agent', 'Agent')], max_length=20),
        ),
    ]
